deploy-to-server:
  stage: deploy
  only:
    - master
  before_script:
    - echo 'start deployment'
    - whoami
  script:
    - cd /home/ubuntu/s03p12a112/backend/
    - sudo mvn package
    - cd /home/ubuntu/s03p12a112/backend/target/
    - kill $(lsof -t -i:8000)
    - setsid nohup java -jar backend-0.0.1-SNAPSHOT.jar &
    - cd /home/ubuntu/s03p12a112/frontend/
    - sudo npm run build
    - sudo service nginx restart
  after_script:
    - echo 'deployment is done'
  tags:
    - deploy